INSERT INTO GAMBLER.COUNTRY (name) VALUES ('India');
INSERT INTO GAMBLER.COUNTRY (name) VALUES ('Brazil');
INSERT INTO GAMBLER.COUNTRY (name) VALUES ('USA');
INSERT INTO GAMBLER.COUNTRY (name) VALUES ('Italy');